from typing import Optional

def _(s: object) -> str: ...
def gettext(s: object) -> str: ...
def ngettext(singular: object, plural: object, n: int) -> str: ...
def install(domain: str, localedir: Optional[str] = None) -> None: ...
